import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])
b = np.array([ [1, 3, 5],  [8, 5, 6], [7, 1, 6]])
print("Matrix a = ")
print(a)
print("\nMatrix b = ")
print(b)
print("\nMatrix Additon = ") 
print(np.add(a,b))
print("\nMatrix subtraction = ") 
print(np.subtract(a,b))
print("\nMatrix Multiplication = ") 
print(np.dot(a,b),"\n")
print("\nTranspose of matrix a = ") 
print(np.transpose(a))